# Generated by Django 4.1.4 on 2022-12-19 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sweet', '0002_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
